import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c6c6cb",
        "on-secondary-container": "#e4e7ff",
        "surface-container": "#1d2022",
        "surface-container-lowest": "#0b0f10",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#323537",
        "on-secondary-fixed": "#001551",
        "surface-container-highest": "#323537",
        "surface-container-low": "#191c1e",
        "background": "#101415",
        "tertiary": "#4edea3",
        "on-primary": "#2d3137",
        "inverse-surface": "#e0e3e5",
        "primary": "#c3c6cf",
        "error-container": "#93000a",
        "on-tertiary": "#003824",
        "on-surface": "#e0e3e5",
        "primary-fixed": "#dfe2eb",
        "outline": "#8f9095",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-container": "#001108",
        "inverse-on-surface": "#2d3133",
        "surface-bright": "#363a3b",
        "secondary": "#b6c4ff",
        "surface-dim": "#101415",
        "secondary-container": "#0356ff",
        "primary-fixed-dim": "#c3c6cf",
        "primary-container": "#0a0e14",
        "on-primary-fixed": "#181c22",
        "secondary-fixed": "#dce1ff",
        "on-background": "#e0e3e5",
        "on-secondary-fixed-variant": "#0039b3",
        "surface-container-high": "#272a2c",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#002113",
        "outline-variant": "#45474b",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#43474e",
        "secondary-fixed-dim": "#b6c4ff",
        "surface": "#101415",
        "on-secondary": "#002780",
        "inverse-primary": "#5b5e66",
        "surface-tint": "#c3c6cf",
        "on-primary-container": "#787b83",
        "on-tertiary-container": "#008c60",
        "fito-navy": "#0b0f10",
        "fito-blue": "#0356ff",
        "fito-green": "#4edea3",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        heading: ["var(--font-space-grotesk)"],
      },
      borderRadius: {
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
      spacing: {
        gutter: "24px",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
